### ISSUE TITLE
Error in EconEvalClasses

### ISSUE THREAD

**Issue by rezayas** [yaesoubilab/SimPy#37]
In the file `TestEconEval_CEA.py`, in line 42, I get an error if instead of 
`print(myCEA.build_CE_table(ce.Interval.PREDICTION))`
I use
`print(myCEA.build_CE_table())`.

In other words, the code doesn't like it when we ask for the CE table without intervals.

**Comment by yanqi8** [comment]
Sorry I think I forgot to implement the table without intervals 😂 It should be fine now.

**Comment by rezayas** [comment]
perfect. thank you.
